package Modelo;
// Generated May 8, 2017 10:51:18 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Noticias generated by hbm2java
 */
public class Noticias implements java.io.Serializable {

    private Integer noticiaId;
    private Usuarios usuarios;
    private String tituloNoticia;
    private String textoNoticia;
    private Date fecha;

    public Noticias() {
    }

    public Noticias(Usuarios usuarios, String tituloNoticia, String textoNoticia, Date fecha) {
        this.usuarios = usuarios;
        this.tituloNoticia = tituloNoticia;
        this.textoNoticia = textoNoticia;
        this.fecha = fecha;
    }

    public Integer getNoticiaId() {
        return this.noticiaId;
    }

    public void setNoticiaId(Integer noticiaId) {
        this.noticiaId = noticiaId;
    }

    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public String getTituloNoticia() {
        return this.tituloNoticia;
    }

    public void setTituloNoticia(String tituloNoticia) {
        this.tituloNoticia = tituloNoticia;
    }

    public String getTextoNoticia() {
        return this.textoNoticia;
    }

    public void setTextoNoticia(String textoNoticia) {
        this.textoNoticia = textoNoticia;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Override
    public String toString() {
        return "Noticias{" + "noticiaId=" + noticiaId + ", usuarios=" + usuarios + ", tituloNoticia=" + tituloNoticia + ", textoNoticia=" + textoNoticia + ", fecha=" + fecha + '}';
    }

}
