package Modelo;
// Generated May 7, 2017 4:44:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Noticias generated by hbm2java
 */
public class Noticias  implements java.io.Serializable {


     private Integer noticiaId;
     private String tituloNoticia;
     private String textoNoticia;
     private Date fecha;
     private int usuarioId;

    public Noticias() {
    }

    public Noticias(String tituloNoticia, String textoNoticia, Date fecha, int usuarioId) {
       this.tituloNoticia = tituloNoticia;
       this.textoNoticia = textoNoticia;
       this.fecha = fecha;
       this.usuarioId = usuarioId;
    }
   
    public Integer getNoticiaId() {
        return this.noticiaId;
    }
    
    public void setNoticiaId(Integer noticiaId) {
        this.noticiaId = noticiaId;
    }
    public String getTituloNoticia() {
        return this.tituloNoticia;
    }
    
    public void setTituloNoticia(String tituloNoticia) {
        this.tituloNoticia = tituloNoticia;
    }
    public String getTextoNoticia() {
        return this.textoNoticia;
    }
    
    public void setTextoNoticia(String textoNoticia) {
        this.textoNoticia = textoNoticia;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }




}


