package Modelo;
// Generated May 7, 2017 4:44:48 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer usuarioId;
     private String nickUsuario;
     private String nombreUsuario;
     private String apellidoUsuario;
     private String numeroUsuario;
     private String correoUsuario;
     private String claveUsuario;

    public Usuarios() {
    }

    public Usuarios(String nickUsuario, String nombreUsuario, String apellidoUsuario, String numeroUsuario, String correoUsuario, String claveUsuario) {
       this.nickUsuario = nickUsuario;
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.numeroUsuario = numeroUsuario;
       this.correoUsuario = correoUsuario;
       this.claveUsuario = claveUsuario;
    }
   
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getNickUsuario() {
        return this.nickUsuario;
    }
    
    public void setNickUsuario(String nickUsuario) {
        this.nickUsuario = nickUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }
    public String getNumeroUsuario() {
        return this.numeroUsuario;
    }
    
    public void setNumeroUsuario(String numeroUsuario) {
        this.numeroUsuario = numeroUsuario;
    }
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }
    public String getClaveUsuario() {
        return this.claveUsuario;
    }
    
    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }




}


