package Modelo;
// Generated May 8, 2017 10:51:18 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

    private String nickUsuario;
    private String nombreUsuario;
    private String apellidoUsuario;
    private String numeroUsuario;
    private String correoUsuario;
    private String claveUsuario;
    private Set noticiases = new HashSet(0);

    public Usuarios() {
    }

    public Usuarios(String nickUsuario, String nombreUsuario, String apellidoUsuario, String numeroUsuario, String correoUsuario, String claveUsuario) {
        this.nickUsuario = nickUsuario;
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.numeroUsuario = numeroUsuario;
        this.correoUsuario = correoUsuario;
        this.claveUsuario = claveUsuario;
    }

    public Usuarios(String nickUsuario, String nombreUsuario, String apellidoUsuario, String numeroUsuario, String correoUsuario, String claveUsuario, Set noticiases) {
        this.nickUsuario = nickUsuario;
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.numeroUsuario = numeroUsuario;
        this.correoUsuario = correoUsuario;
        this.claveUsuario = claveUsuario;
        this.noticiases = noticiases;
    }

    public String getNickUsuario() {
        return this.nickUsuario;
    }

    public void setNickUsuario(String nickUsuario) {
        this.nickUsuario = nickUsuario;
    }

    public String getNombreUsuario() {
        return this.nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }

    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }

    public String getNumeroUsuario() {
        return this.numeroUsuario;
    }

    public void setNumeroUsuario(String numeroUsuario) {
        this.numeroUsuario = numeroUsuario;
    }

    public String getCorreoUsuario() {
        return this.correoUsuario;
    }

    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }

    public String getClaveUsuario() {
        return this.claveUsuario;
    }

    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }

    public Set getNoticiases() {
        return this.noticiases;
    }

    public void setNoticiases(Set noticiases) {
        this.noticiases = noticiases;
    }

    @Override
    public String toString() {
        return "Usuarios{" + "nickUsuario=" + nickUsuario + ", nombreUsuario=" + nombreUsuario + ", apellidoUsuario=" + apellidoUsuario + ", numeroUsuario=" + numeroUsuario + ", correoUsuario=" + correoUsuario + ", claveUsuario=" + claveUsuario + ", noticiases=" + noticiases + '}';
    }

}
